// Database of 200 games with all-time player counts (in millions)
const games = [
    { name: "Minecraft",                          players: 738,  image: "src/images/minecraft.png" },
    { name: "Grand Theft Auto V",                 players: 200,  image: "src/images/grand-theft-auto-v.png" },
    { name: "Tetris",                             players: 520,  image: "src/images/tetris.png" },
    { name: "Wii Sports",                         players: 82,   image: "src/images/wii-sports.png" },
    { name: "PUBG",                               players: 400,  image: "src/images/pubg.png" },
    { name: "Mario Kart 8",                       players: 64,   image: "src/images/mario-kart-8.png" },
    { name: "Super Mario Bros.",                  players: 58,   image: "src/images/super-mario-bros.png" },
    { name: "Red Dead Redemption 2",              players: 65,   image: "src/images/red-dead-redemption-2.png" },
    { name: "The Witcher 3",                      players: 50,   image: "src/images/the-witcher-3.png" },
    { name: "Pokémon Red/Blue",                   players: 47,   image: "src/images/pokemon-red-blue.png" },
    { name: "Fortnite",                           players: 650,  image: "src/images/fortnite.png" },
    { name: "Elden Ring",                         players: 25,   image: "src/images/elden-ring.png" },
    { name: "Call of Duty: Modern Warfare",       players: 75,   image: "src/images/call-of-duty-modern-warfare.png" },
    { name: "FIFA 23",                            players: 45,   image: "src/images/fifa-23.png" },
    { name: "Among Us",                           players: 500,  image: "src/images/among-us.png" },
    { name: "Overwatch 2",                        players: 35,   image: "src/images/overwatch-2.png" },
    { name: "League of Legends",                  players: 180,  image: "src/images/league-of-legends.png" },
    { name: "Valorant",                           players: 35,   image: "src/images/valorant.png" },
    { name: "Apex Legends",                       players: 130,  image: "src/images/apex-legends.png" },
    { name: "Roblox",                             players: 380,  image: "src/images/roblox.png" },
    { name: "Counter-Strike 2",                   players: 100,  image: "src/images/counter-strike-2.png" },
    { name: "Diablo IV",                          players: 20,   image: "src/images/diablo-iv.png" },
    { name: "Hogwarts Legacy",                    players: 24,   image: "src/images/hogwarts-legacy.png" },
    { name: "The Legend of Zelda: BOTW",          players: 32,   image: "src/images/the-legend-of-zelda-botw.png" },
    { name: "God of War (2018)",                  players: 23,   image: "src/images/god-of-war-2018.png" },
    { name: "Cyberpunk 2077",                     players: 30,   image: "src/images/cyberpunk-2077.png" },
    { name: "Animal Crossing: New Horizons",      players: 44,   image: "src/images/animal-crossing-new-horizons.png" },
    { name: "The Sims 4",                         players: 70,   image: "src/images/the-sims-4.png" },
    { name: "Genshin Impact",                     players: 120,  image: "src/images/genshin-impact.png" },
    { name: "Candy Crush Saga",                   players: 500,  image: "src/images/candy-crush-saga.png" },
    { name: "Clash of Clans",                     players: 500,  image: "src/images/clash-of-clans.png" },
    { name: "Dota 2",                             players: 150,  image: "src/images/dota-2.png" },
    { name: "World of Warcraft",                  players: 150,  image: "src/images/world-of-warcraft.png" },
    { name: "Hearthstone",                        players: 150,  image: "src/images/hearthstone.png" },
    { name: "Fall Guys",                          players: 80,   image: "src/images/fall-guys.png" },
    { name: "Rocket League",                      players: 100,  image: "src/images/rocket-league.png" },
    { name: "Dark Souls III",                     players: 15,   image: "src/images/dark-souls-iii.png" },
    { name: "Sekiro: Shadows Die Twice",          players: 10,   image: "src/images/sekiro.png" },
    { name: "Monster Hunter: World",              players: 25,   image: "src/images/monster-hunter-world.png" },
    { name: "Final Fantasy VII Remake",           players: 10,   image: "src/images/final-fantasy-vii-remake.png" },
    { name: "Resident Evil Village",              players: 12,   image: "src/images/resident-evil-village.png" },
    { name: "Horizon Zero Dawn",                  players: 24,   image: "src/images/horizon-zero-dawn.png" },
    { name: "Spider-Man (PS4)",                   players: 33,   image: "src/images/spider-man-ps4.png" },
    { name: "Ghost of Tsushima",                  players: 13,   image: "src/images/ghost-of-tsushima.png" },
    { name: "Halo Infinite",                      players: 30,   image: "src/images/halo-infinite.png" },
    { name: "Destiny 2",                          players: 100,  image: "src/images/destiny-2.png" },
    { name: "Borderlands 3",                      players: 18,   image: "src/images/borderlands-3.png" },
    { name: "Sea of Thieves",                     players: 40,   image: "src/images/sea-of-thieves.png" },
    { name: "Terraria",                           players: 58,   image: "src/images/terraria.png" },
    { name: "Stardew Valley",                     players: 30,   image: "src/images/stardew-valley.png" },
    { name: "Hades",                              players: 5,    image: "src/images/hades.png" },
    { name: "Hollow Knight",                      players: 5,    image: "src/images/hollow-knight.png" },
    { name: "Celeste",                            players: 2,    image: "src/images/celeste.png" },
    { name: "Dead by Daylight",                   players: 50,   image: "src/images/dead-by-daylight.png" },
    { name: "Phasmophobia",                       players: 12,   image: "src/images/phasmophobia.png" },
    { name: "Rust",                               players: 15,   image: "src/images/rust.png" },
    { name: "ARK: Survival Evolved",              players: 20,   image: "src/images/ark-survival-evolved.png" },
    { name: "No Man's Sky",                       players: 15,   image: "src/images/no-mans-sky.png" },
    { name: "Subnautica",                         players: 8,    image: "src/images/subnautica.png" },
    { name: "The Forest",                         players: 10,   image: "src/images/the-forest.png" },
    { name: "Satisfactory",                       players: 5,    image: "src/images/satisfactory.png" },
    { name: "Factorio",                           players: 4,    image: "src/images/factorio.png" },
    { name: "Cities: Skylines",                   players: 12,   image: "src/images/cities-skylines.png" },
    { name: "Planet Coaster",                     players: 4,    image: "src/images/planet-coaster.png" },
    { name: "Euro Truck Simulator 2",             players: 15,   image: "src/images/euro-truck-simulator-2.png" },
    { name: "Microsoft Flight Simulator",         players: 10,   image: "src/images/microsoft-flight-simulator.png" },
    { name: "Farming Simulator 22",               players: 6,    image: "src/images/farming-simulator-22.png" },
    { name: "The Crew 2",                         players: 8,    image: "src/images/the-crew-2.png" },
    { name: "Forza Horizon 5",                    players: 35,   image: "src/images/forza-horizon-5.png" },
    { name: "Gran Turismo 7",                     players: 15,   image: "src/images/gran-turismo-7.png" },
    { name: "Need for Speed Heat",                players: 8,    image: "src/images/need-for-speed-heat.png" },
    { name: "Assetto Corsa",                      players: 6,    image: "src/images/assetto-corsa.png" },
    { name: "F1 23",                              players: 5,    image: "src/images/f1-23.png" },
    { name: "NBA 2K24",                           players: 20,   image: "src/images/nba-2k24.png" },
    { name: "Madden NFL 24",                      players: 15,   image: "src/images/madden-nfl-24.png" },
    { name: "MLB The Show 23",                    players: 8,    image: "src/images/mlb-the-show-23.png" },
    { name: "WWE 2K23",                           players: 6,    image: "src/images/wwe-2k23.png" },
    { name: "eFootball 2024",                     players: 50,   image: "src/images/efootball-2024.png" },
    { name: "Mortal Kombat 11",                   players: 15,   image: "src/images/mortal-kombat-11.png" },
    { name: "Street Fighter 6",                   players: 5,    image: "src/images/street-fighter-6.png" },
    { name: "Tekken 7",                           players: 12,   image: "src/images/tekken-7.png" },
    { name: "Super Smash Bros. Ultimate",         players: 33,   image: "src/images/super-smash-bros-ultimate.png" },
    { name: "Dragon Ball FighterZ",               players: 10,   image: "src/images/dragon-ball-fighterz.png" },
    { name: "Guilty Gear Strive",                 players: 3,    image: "src/images/guilty-gear-strive.png" },
    { name: "Splatoon 3",                         players: 12,   image: "src/images/splatoon-3.png" },
    { name: "Pokemon Scarlet/Violet",             players: 25,   image: "src/images/pokemon-scarlet-violet.png" },
    { name: "Pokemon GO",                         players: 600,  image: "src/images/pokemon-go.png" },
    { name: "Clash Royale",                       players: 300,  image: "src/images/clash-royale.png" },
    { name: "Brawl Stars",                        players: 400,  image: "src/images/brawl-stars.png" },
    { name: "Mobile Legends",                     players: 1000, image: "src/images/mobile-legends.png" },
    { name: "Free Fire",                          players: 1500, image: "src/images/free-fire.png" },
    { name: "PUBG Mobile",                        players: 1200, image: "src/images/pbm.png" },
    { name: "Call of Duty Mobile",                players: 650,  image: "src/images/callDm.png" },
    { name: "Subway Surfers",                     players: 3000, image: "src/images/sub.png" },
    { name: "Temple Run",                         players: 1000, image: "src/images/temp.png" },
    { name: "Angry Birds",                        players: 500,  image: "src/images/birds.png" },
    { name: "Fruit Ninja",                        players: 300,  image: "src/images/fruit.png" },
    { name: "Cut the Rope",                       players: 250,  image: "src/images/cut.png" },
    { name: "Plants vs. Zombies",                 players: 150,  image: "src/images/pvz.png" },
    { name: "Crossy Road",                        players: 200,  image: "src/images/crossy.png" },
    { name: "8 Ball Pool",                        players: 500,  image: "src/images/8.png" },
    { name: "Asphalt 9",                          players: 100,  image: "src/images/9.png" },
    { name: "Geometry Dash",                      players: 100,  image: "src/images/geometry-dash.png" },
    { name: "Stumble Guys",                       players: 200,  image: "src/images/sg.png" },
    { name: "Human Fall Flat",                    players: 40,   image: "src/images/hff.png" },
    { name: "Gang Beasts",                        players: 10,   image: "src/images/gb.png" },
    { name: "Overcooked 2",                       players: 8,    image: "src/images/oc2.png" },
    { name: "It Takes Two",                       players: 16,   image: "src/images/itt.png" },
    { name: "A Way Out",                          players: 6,    image: "src/images/awo.png" },
    { name: "Unravel Two",                        players: 4,    image: "src/images/ut.png" },
    { name: "Little Nightmares II",               players: 5,    image: "src/images/ln2.png" },
    { name: "Inside",                             players: 3,    image: "src/images/in.png" },
    { name: "Limbo",                              players: 4,    image: "src/images/lim.png" },
    { name: "Cuphead",                            players: 6,    image: "src/images/cup.png" },
    { name: "Ori and the Will of the Wisps",      players: 5,    image: "src/images/ori.png" },
    { name: "Psychonauts 2",                      players: 2,    image: "src/images/psy.png" },
    { name: "Ratchet & Clank: Rift Apart",        players: 5,    image: "src/images/rat.png" },
    { name: "Sackboy: A Big Adventure",           players: 4,    image: "src/images/sack.png" },
    { name: "Astro's Playroom",                   players: 20,   image: "src/images/astro.png" },
    { name: "Returnal",                           players: 3,    image: "src/images/re.png" },
    { name: "Deathloop",                          players: 3,    image: "src/images/de.png" },
    { name: "Hitman 3",                           players: 15,   image: "src/images/hit.png" },
    { name: "Dishonored 2",                       players: 5,    image: "src/images/dis.png" },
    { name: "Prey (2017)",                        players: 3,    image: "src/images/pre.png" },
    { name: "Control",                            players: 6,    image: "src/images/cont.png" },
    { name: "Alan Wake 2",                        players: 2,    image: "src/images/ala.png" },
    { name: "Death Stranding",                    players: 10,   image: "src/images/dea.png" },
    { name: "Metal Gear Solid V",                 players: 12,   image: "src/images/mgs.png" },
    { name: "Assassin's Creed Valhalla",          players: 25,   image: "src/images/av.png" },
    { name: "Far Cry 6",                          players: 12,   image: "src/images/fc6.png" },
    { name: "Watch Dogs Legion",                  players: 8,    image: "src/images/wd.png" },
    { name: "Rainbow Six Siege",                  players: 85,   image: "src/images/r6.png" },
    { name: "The Division 2",                     players: 20,   image: "src/images/d2.png" },
    { name: "Ghost Recon Wildlands",              players: 15,   image: "src/images/grw.png" },
    { name: "For Honor",                          players: 25,   image: "src/images/fh.png" },
    { name: "Steep",                              players: 5,    image: "src/images/steep.png" },
    { name: "Riders Republic",                    players: 3,    image: "src/images/rr.png" },
    { name: "Just Dance 2024",                    players: 8,    image: "src/images/jd.png" },
    { name: "Beat Saber",                         players: 4,    image: "src/images/bs.png" },
    { name: "Half-Life: Alyx",                    players: 2,    image: "src/images/half.png" },
    { name: "The Elder Scrolls V: Skyrim",        players: 60,   image: "src/images/the.png" },
    { name: "Fallout 4",                          players: 25,   image: "src/images/fal.png" },
    { name: "Starfield",                          players: 14,   image: "src/images/star.png" },
    { name: "Baldur's Gate 3",                    players: 15,   image: "src/images/bal.png" },
    { name: "Divinity: Original Sin 2",           players: 5,    image: "src/images/div.png" },
    { name: "Disco Elysium",                      players: 3,    image: "src/images/disco.png" },
    { name: "Persona 5 Royal",                    players: 8,    image: "src/images/per.png" },
    { name: "Fire Emblem: Three Houses",          players: 6,    image: "src/images/fir.png" },
    { name: "Xenoblade Chronicles 3",             players: 3,    image: "src/images/xen.png" },
    { name: "Tales of Arise",                     players: 3,    image: "src/images/toa.png" },
    { name: "Triangle Strategy",                  players: 2,    image: "src/images/ts.png" },
    { name: "Octopath Traveler II",               players: 2,    image: "src/images/ot22.png" },
    { name: "Live A Live",                        players: 1,    image: "src/images/live.png" },
    { name: "Crisis Core Final Fantasy VII",      players: 2,    image: "src/images/crisis.png" },
    { name: "Bravely Default II",                 players: 1,    image: "src/images/brav.png" },
    { name: "Dragon Quest XI",                    players: 7,    image: "src/images/drag.png" },
    { name: "Nier: Automata",                     players: 8,    image: "src/images/nier.png" },
    { name: "Kingdom Hearts III",                 players: 10,   image: "src/images/king.png" },
    { name: "Final Fantasy XVI",                  players: 4,    image: "src/images/final.png" },
    { name: "Star Wars Jedi: Survivor",           players: 6,    image: "src/images/sws.png" },
    { name: "Star Wars Jedi: Fallen Order",       players: 20,   image: "src/images/swsg.png" },
    { name: "Lego Star Wars: Skywalker Saga",     players: 15,   image: "src/images/lsw.png" },
    { name: "Lego Marvel Super Heroes",           players: 10,   image: "src/images/lms.png" },
    { name: "Lego Batman 3",                      players: 5,    image: "src/images/lb3.png" },
    { name: "Crash Bandicoot 4",                  players: 5,    image: "src/images/cra4.png" },
    { name: "Spyro Reignited Trilogy",            players: 10,   image: "src/images/spy.png" },
    { name: "Sonic Frontiers",                    players: 5,    image: "src/images/son.png" },
    { name: "Sonic Mania",                        players: 5,    image: "src/images/som.png" },
    { name: "Kirby and the Forgotten Land",       players: 6,    image: "src/images/kir.png" },
    { name: "Yoshi's Crafted World",              players: 4,    image: "src/images/yos.png" },
    { name: "Donkey Kong Country: TF",            players: 5,    image: "src/images/donk.png" },
    { name: "New Super Mario Bros. U",            players: 15,   image: "src/images/nes.png" },
    { name: "Super Mario 3D World",               players: 13,   image: "src/images/smo.png" },
    { name: "Super Mario Odyssey",                players: 27,   image: "src/images/smoo.png" },
    { name: "Luigi's Mansion 3",                  players: 12,   image: "src/images/lug.png" },
    { name: "Paper Mario: Origami King",          players: 4,    image: "src/images/pap.png" },
    { name: "Super Mario Maker 2",                players: 8,    image: "src/images/smm2.png" },
    { name: "New Pokémon Snap",                   players: 3,    image: "src/images/nps.png" },
    { name: "Pokémon Legends: Arceus",            players: 15,   image: "src/images/pla.png" },
    { name: "Pokémon Sword/Shield",               players: 26,   image: "src/images/pss.png" },
    { name: "Metroid Dread",                      players: 3,    image: "src/images/met.png" },
    { name: "The Legend of Zelda: TOTK",          players: 21,   image: "src/images/zel.png" },
    { name: "Link's Awakening (2019)",            players: 7,    image: "src/images/link.png"},
    { name: "Pikmin 4",                           players: 3,    image: "src/images/pikm.png" },
    { name: "Bayonetta 3",                        players: 2,    image: "src/images/bay.png" },
];
 
export default games;