// Database of 200 games with all-time player counts (in millions)
const games = [
    { name: "Minecraft",                          players: 738,  image: "src/images/minecraft.png" },
    { name: "Grand Theft Auto V",                 players: 200,  image: "src/images/grand-theft-auto-v.png" },
    { name: "Tetris",                             players: 520,  image: "src/images/tetris.png" },
    { name: "Wii Sports",                         players: 82,   image: "src/images/wii-sports.png" },
    { name: "PUBG",                               players: 400,  image: "src/images/pubg.png" },
    { name: "Mario Kart 8",                       players: 64,   image: "src/images/mario-kart-8.png" },
    { name: "Super Mario Bros.",                  players: 58,   image: "https://upload.wikimedia.org/wikipedia/en/0/03/Super_Mario_Bros._box.png" },
    { name: "Red Dead Redemption 2",              players: 65,   image: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg" },
    { name: "The Witcher 3",                      players: 50,   image: "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg" },
    { name: "Pokémon Red/Blue",                   players: 47,   image: "https://upload.wikimedia.org/wikipedia/en/a/af/Pok%C3%A9mon_Red_and_Blue_cover_art.webp" },
    { name: "Fortnite",                           players: 650,  image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Fortnite_%28Full_Color%29_-_Logo.png" },
    { name: "Elden Ring",                         players: 25,   image: "https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg" },
    { name: "Call of Duty: Modern Warfare",       players: 75,   image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Call_of_Duty_Modern_Warfare_%282019%29_cover.jpg" },
    { name: "FIFA 23",                            players: 45,   image: "https://upload.wikimedia.org/wikipedia/en/a/a6/FIFA_23_Cover.jpg" },
    { name: "Among Us",                           players: 500,  image: "https://upload.wikimedia.org/wikipedia/en/9/9a/Among_Us_cover_art.jpg" },
    { name: "Overwatch 2",                        players: 35,   image: "https://upload.wikimedia.org/wikipedia/en/c/c0/Overwatch_2_key_art.jpg" },
    { name: "League of Legends",                  players: 180,  image: "https://upload.wikimedia.org/wikipedia/commons/d/d8/League_of_Legends_2019_vector.svg" },
    { name: "Valorant",                           players: 35,   image: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Valorant_logo_-_pink_color_version.svg" },
    { name: "Apex Legends",                       players: 130,  image: "https://upload.wikimedia.org/wikipedia/en/d/db/Apex_legends_cover.jpg" },
    { name: "Roblox",                             players: 380,  image: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Roblox_player_icon_black.svg" },
    { name: "Counter-Strike 2",                   players: 100,  image: "https://upload.wikimedia.org/wikipedia/en/f/f2/CS2_Cover_Art.jpg" },
    { name: "Diablo IV",                          players: 20,   image: "https://upload.wikimedia.org/wikipedia/en/1/1c/Diablo_IV_cover_art.png" },
    { name: "Hogwarts Legacy",                    players: 24,   image: "https://upload.wikimedia.org/wikipedia/en/c/c5/Hogwarts_Legacy_cover_art.png" },
    { name: "The Legend of Zelda: BOTW",          players: 32,   image: "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg" },
    { name: "God of War (2018)",                  players: 23,   image: "https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg" },
    { name: "Cyberpunk 2077",                     players: 30,   image: "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg" },
    { name: "Animal Crossing: New Horizons",      players: 44,   image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg" },
    { name: "The Sims 4",                         players: 70,   image: "https://upload.wikimedia.org/wikipedia/en/7/7e/The_Sims_4_Box_Art.png" },
    { name: "Genshin Impact",                     players: 120,  image: "https://upload.wikimedia.org/wikipedia/en/5/5d/Genshin_Impact_cover.jpg" },
    { name: "Candy Crush Saga",                   players: 500,  image: "https://upload.wikimedia.org/wikipedia/en/6/6e/Candy_Crush_Saga_app_icon.png" },
    { name: "Clash of Clans",                     players: 500,  image: "https://upload.wikimedia.org/wikipedia/en/5/59/Clashofclans.png" },
    { name: "Dota 2",                             players: 150,  image: "https://upload.wikimedia.org/wikipedia/en/0/09/Dota_2_logo.png" },
    { name: "World of Warcraft",                  players: 150,  image: "https://upload.wikimedia.org/wikipedia/en/6/65/World_of_Warcraft.png" },
    { name: "Hearthstone",                        players: 150,  image: "https://upload.wikimedia.org/wikipedia/en/1/1e/Hearthstone_Logo.png" },
    { name: "Fall Guys",                          players: 80,   image: "https://upload.wikimedia.org/wikipedia/en/5/5e/Fall_Guys_cover.jpg" },
    { name: "Rocket League",                      players: 100,  image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Rocket_League_coverart.jpg" },
    { name: "Dark Souls III",                     players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg" },
    { name: "Sekiro",                             players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg" },
    { name: "Monster Hunter: World",              players: 25,   image: "https://upload.wikimedia.org/wikipedia/en/1/1b/Monster_Hunter_World_cover_art.jpg" },
    { name: "Final Fantasy VII Remake",           players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/c/ce/FFVIIRemake.png" },
    { name: "Resident Evil Village",              players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png" },
    { name: "Horizon Zero Dawn",                  players: 24,   image: "https://upload.wikimedia.org/wikipedia/en/9/93/Horizon_Zero_Dawn.jpg" },
    { name: "Spider-Man (PS4)",                   players: 33,   image: "https://upload.wikimedia.org/wikipedia/en/e/e1/Spider-Man_PS4_cover.jpg" },
    { name: "Ghost of Tsushima",                  players: 13,   image: "https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg" },
    { name: "Halo Infinite",                      players: 30,   image: "https://upload.wikimedia.org/wikipedia/en/1/14/Halo_Infinite.png" },
    { name: "Destiny 2",                          players: 100,  image: "https://upload.wikimedia.org/wikipedia/en/0/05/Destiny_2_%28artwork%29.jpg" },
    { name: "Borderlands 3",                      players: 18,   image: "https://upload.wikimedia.org/wikipedia/en/5/55/Borderlands_3_cover_art.jpg" },
    { name: "Sea of Thieves",                     players: 40,   image: "https://upload.wikimedia.org/wikipedia/en/3/38/Sea_of_Thieves_cover_art.jpg" },
    { name: "Terraria",                           players: 58,   image: "https://upload.wikimedia.org/wikipedia/en/1/1a/Terraria_Steam_artwork.jpg" },
    { name: "Stardew Valley",                     players: 30,   image: "https://upload.wikimedia.org/wikipedia/en/f/fd/Logo_of_Stardew_Valley.png" },
    { name: "Hades",                              players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg" },
    { name: "Hollow Knight",                      players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/0/04/Hollow_Knight_first_cover_art.webp" },
    { name: "Celeste",                            players: 2,    image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Celeste_box_art_full.png" },
    { name: "Dead by Daylight",                   players: 50,   image: "https://upload.wikimedia.org/wikipedia/en/b/b5/Dead_by_Daylight_Steam_header.jpg" },
    { name: "Phasmophobia",                       players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/4/40/Phasmophobia_cover_art.jpg" },
    { name: "Rust",                               players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/1/14/Rust_video_game_cover.jpg" },
    { name: "ARK: Survival Evolved",              players: 20,   image: "https://upload.wikimedia.org/wikipedia/en/c/c6/ARK_Survival_Evolved_cover_art.png" },
    { name: "No Man's Sky",                       players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/6/67/No_Man%27s_Sky.jpg" },
    { name: "Subnautica",                         players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/6/6d/Subnautica_cover_art.jpg" },
    { name: "The Forest",                         players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/4/49/The_Forest_%28video_game%29_cover.jpg" },
    { name: "Satisfactory",                       players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/a/a5/Satisfactory_cover.jpg" },
    { name: "Factorio",                           players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/2/22/Factorio-logo.jpg" },
    { name: "Cities: Skylines",                   players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/5/5e/Cities_Skylines_cover_art.jpg" },
    { name: "Planet Coaster",                     players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/2/21/Planet_Coaster_cover.jpg" },
    { name: "Euro Truck Simulator 2",             players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/5/52/Euro_Truck_Simulator_2_cover.jpg" },
    { name: "Microsoft Flight Simulator",         players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/2/2d/Microsoft_Flight_Simulator_%282020%29_cover_art.png" },
    { name: "Farming Simulator 22",               players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/4/47/Farming_Simulator_22_cover_art.jpg" },
    { name: "The Crew 2",                         players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/2/25/The_Crew_2_cover.jpg" },
    { name: "Forza Horizon 5",                    players: 35,   image: "https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg" },
    { name: "Gran Turismo 7",                     players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/1/14/Gran_Turismo_7_cover_art.jpg" },
    { name: "Need for Speed Heat",                players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/8/8f/NFS_Heat_Cover_Art.jpg" },
    { name: "Assetto Corsa",                      players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/f/fb/Assetto_Corsa_cover.jpg" },
    { name: "F1 23",                              players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/2/21/F1_23_cover.jpg" },
    { name: "NBA 2K24",                           players: 20,   image: "https://upload.wikimedia.org/wikipedia/en/1/18/NBA_2K24_cover.jpg" },
    { name: "Madden NFL 24",                      players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/7/71/Madden_NFL_24_cover.jpg" },
    { name: "MLB The Show 23",                    players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/4/4c/MLB_The_Show_23_cover.jpg" },
    { name: "WWE 2K23",                           players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/8/87/WWE_2K23_cover_art.jpg" },
    { name: "eFootball 2024",                     players: 50,   image: "https://upload.wikimedia.org/wikipedia/en/0/04/EFootball_2024_logo.png" },
    { name: "Mortal Kombat 11",                   players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/6/6c/Mortal_Kombat_11_cover_art.png" },
    { name: "Street Fighter 6",                   players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/2/2b/Street_Fighter_6_logo.png" },
    { name: "Tekken 7",                           players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/0/0b/Tekken_7.png" },
    { name: "Super Smash Bros. Ultimate",         players: 33,   image: "https://upload.wikimedia.org/wikipedia/en/5/50/Super_Smash_Bros._Ultimate.jpg" },
    { name: "Dragon Ball FighterZ",               players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/7/7d/Dragon_Ball_FighterZ_cover_art.jpg" },
    { name: "Guilty Gear Strive",                 players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/3/3a/Guilty_Gear_Strive_cover_art.jpg" },
    { name: "Splatoon 3",                         players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/3/33/Splatoon_3_box_art.jpg" },
    { name: "Pokemon Scarlet/Violet",             players: 25,   image: "https://upload.wikimedia.org/wikipedia/en/3/38/Pok%C3%A9mon_Scarlet_and_Violet.jpg" },
    { name: "Pokemon GO",                         players: 600,  image: "https://upload.wikimedia.org/wikipedia/commons/2/23/Pok%C3%A9mon_GO_logo.svg" },
    { name: "Clash Royale",                       players: 300,  image: "https://upload.wikimedia.org/wikipedia/en/1/1e/Clash_Royale.png" },
    { name: "Brawl Stars",                        players: 400,  image: "https://upload.wikimedia.org/wikipedia/en/a/a6/Brawl_Stars_logo.png" },
    { name: "Mobile Legends",                     players: 1000, image: "https://upload.wikimedia.org/wikipedia/en/2/2f/Mobile_Legends_Bang_Bang_logo.png" },
    { name: "Free Fire",                          players: 1500, image: "https://upload.wikimedia.org/wikipedia/en/5/54/Garena_Free_Fire_logo.png" },
   
   
   
   
    { name: "PUBG Mobile",                        players: 1200, image: "src/images/pbm.png" },
    { name: "Call of Duty Mobile",                players: 650,  image: "src/images/callDm.png" },
    { name: "Subway Surfers",                     players: 3000, image: "src/images/sub.png" },
    { name: "Temple Run",                         players: 1000, image: "src/images/temp.pngh" },
    { name: "Angry Birds",                        players: 500,  image: "src/images/birds.png" },
    { name: "Fruit Ninja",                        players: 300,  image: "src/images/fruit.png" },
    { name: "Cut the Rope",                       players: 250,  image: "src/images/cut.png" },
    { name: "Plants vs. Zombies",                 players: 150,  image: "src/images/pvz.png" },
    { name: "Crossy Road",                        players: 200,  image: "src/images/crossy.png" },
    { name: "8 Ball Pool",                        players: 500,  image: "src/images/8.png" },
    { name: "Asphalt 9",                          players: 100,  image: "src/images/9.png" },
    { name: "Geometry Dash",                      players: 100,  image: "src/images/geometry-dash.png" },
    { name: "Stumble Guys",                       players: 200,  image: "src/images/sg.png" },
    { name: "Human Fall Flat",                    players: 40,   image: "src/images/hff.png" },
    { name: "Gang Beasts",                        players: 10,   image: "src/images/gb.png" },
    { name: "Overcooked 2",                       players: 8,    image: "src/images/oc2.png" },
    { name: "It Takes Two",                       players: 16,   image: "src/images/itt.png" },
    { name: "A Way Out",                          players: 6,    image: "src/images/awo.png" },
    { name: "Unravel Two",                        players: 4,    image: "src/images/ut.png" },
    { name: "Little Nightmares II",               players: 5,    image: "src/images/ln2.png" },
    { name: "Inside",                             players: 3,    image: "src/images/in.png" },
    { name: "Limbo",                              players: 4,    image: "src/images/lim.png" },
    { name: "Cuphead",                            players: 6,    image: "src/images/cup.png" },
    { name: "Ori and the Will of the Wisps",      players: 5,    image: "src/images/ori.png" },
    { name: "Psychonauts 2",                      players: 2,    image: "src/images/psy.png" },
    { name: "Ratchet & Clank: Rift Apart",        players: 5,    image: "src/images/rat.png" },
    { name: "Sackboy: A Big Adventure",           players: 4,    image: "src/images/sack.png" },
    { name: "Astro's Playroom",                   players: 20,   image: "src/images/astro.png" },
    { name: "Returnal",                           players: 3,    image: "src/images/re.png" },
    { name: "Deathloop",                          players: 3,    image: "src/images/de.png" },
    { name: "Hitman 3",                           players: 15,   image: "src/images/hit.png" },
    { name: "Dishonored 2",                       players: 5,    image: "src/images/dis.png" },
    { name: "Prey (2017)",                        players: 3,    image: "src/images/pre.png" },
    { name: "Control",                            players: 6,    image: "src/images/cont.png" },
    { name: "Alan Wake 2",                        players: 2,    image: "src/images/ala.png" },
    { name: "Death Stranding",                    players: 10,   image: "src/images/dea.png" },
    { name: "Metal Gear Solid V",                 players: 12,   image: "src/images/mgs.png" },
    { name: "Assassin's Creed Valhalla",          players: 25,   image: "src/images/av.png" },
    { name: "Far Cry 6",                          players: 12,   image: "src/images/fc6.png" },
    { name: "Watch Dogs Legion",                  players: 8,    image: "src/images/wd.png" },
    { name: "Rainbow Six Siege",                  players: 85,   image: "src/images/r6.png" },
    { name: "The Division 2",                     players: 20,   image: "src/images/d2.png" },
    { name: "Ghost Recon Wildlands",              players: 15,   image: "src/images/grw.png" },
    { name: "For Honor",                          players: 25,   image: "src/images/fh.png" },
    { name: "Steep",                              players: 5,    image: "src/images/steep.png" },
    { name: "Riders Republic",                    players: 3,    image: "src/images/rr.png" },
    { name: "Just Dance 2024",                    players: 8,    image: "src/images/jd.png" },
    { name: "Beat Saber",                         players: 4,    image: "src/images/bs.png" },
    { name: "Half-Life: Alyx",                    players: 2,    image: "src/images/half.png" },
    { name: "The Elder Scrolls V: Skyrim",        players: 60,   image: "src/images/the.png" },
    { name: "Fallout 4",                          players: 25,   image: "src/images/fal.png" },
    { name: "Starfield",                          players: 14,   image: "src/images/star.png" },
    { name: "Baldur's Gate 3",                    players: 15,   image: "src/images/bal.png" },
    { name: "Divinity: Original Sin 2",           players: 5,    image: "src/images/div.png" },
    { name: "Disco Elysium",                      players: 3,    image: "src/images/disco.png" },
    { name: "Persona 5 Royal",                    players: 8,    image: "src/images/per.png" },
    { name: "Fire Emblem: Three Houses",          players: 6,    image: "src/images/fir.png" },
    { name: "Xenoblade Chronicles 3",             players: 3,    image: "src/images/xen.png" },
    { name: "Tales of Arise",                     players: 3,    image: "src/images/toa.png" },
    { name: "Triangle Strategy",                  players: 2,    image: "src/images/ts.png" },
    { name: "Octopath Traveler II",               players: 2,    image: "src/images/ot22.png" },
    { name: "Live A Live",                        players: 1,    image: "src/images/live.png" },
    { name: "Crisis Core Final Fantasy VII",      players: 2,    image: "src/images/crisis.png" },
    { name: "Bravely Default II",                 players: 1,    image: "src/images/brav.png" },
    { name: "Dragon Quest XI",                    players: 7,    image: "src/images/drag.png" },
    { name: "Nier: Automata",                     players: 8,    image: "src/images/nier.png" },
    { name: "Kingdom Hearts III",                 players: 10,   image: "src/images/king.png" },
    { name: "Final Fantasy XVI",                  players: 4,    image: "src/images/final.png" },
    { name: "Star Wars Jedi: Survivor",           players: 6,    image: "src/images/sws.png" },
    { name: "Star Wars Jedi: Fallen Order",       players: 20,   image: "src/images/swsg.png" },
    { name: "Lego Star Wars: Skywalker Saga",     players: 15,   image: "src/images/lsw.png" },
    { name: "Lego Marvel Super Heroes",           players: 10,   image: "src/images/lms.png" },
    { name: "Lego Batman 3",                      players: 5,    image: "src/images/lb3.png" },
    { name: "Crash Bandicoot 4",                  players: 5,    image: "src/images/cra4.png" },
    { name: "Spyro Reignited Trilogy",            players: 10,   image: "src/images/spy.png" },
    { name: "Sonic Frontiers",                    players: 5,    image: "src/images/son.png" },
    { name: "Sonic Mania",                        players: 5,    image: "src/images/som.png" },
    { name: "Kirby and the Forgotten Land",       players: 6,    image: "src/images/kir.png" },
    { name: "Yoshi's Crafted World",              players: 4,    image: "src/images/yos.png" },
    { name: "Donkey Kong Country: TF",            players: 5,    image: "src/images/donk.png" },
    { name: "New Super Mario Bros. U",            players: 15,   image: "src/images/nes.png" },
    { name: "Super Mario 3D World",               players: 13,   image: "src/images/smo.png" },
    { name: "Super Mario Odyssey",                players: 27,   image: "src/images/smoo.png" },
    { name: "Luigi's Mansion 3",                  players: 12,   image: "src/images/lug.png" },
    { name: "Paper Mario: Origami King",          players: 4,    image: "src/images/pap.png" },
    { name: "Super Mario Maker 2",                players: 8,    image: "src/images/smm2.png" },
    { name: "New Pokémon Snap",                   players: 3,    image: "src/images/nps.png" },
    { name: "Pokémon Legends: Arceus",            players: 15,   image: "src/images/pla.png" },
    { name: "Pokémon Sword/Shield",               players: 26,   image: "src/images/pss.png" },
    { name: "Metroid Dread",                      players: 3,    image: "src/images/met.png" },
    { name: "The Legend of Zelda: TOTK",          players: 21,   image: "src/images/zel.png" },
    { name: "Link's Awakening (2019)",            players: 7,    image: "src/images/link.png"},
    { name: "Pikmin 4",                           players: 3,    image: "src/images/pikm.png" },
    { name: "Bayonetta 3",                        players: 2,    image: "src/images/bay.png" },
];
 
export default games;