// Database of 200 games with all-time player counts (in millions)
const games = [
    { name: "Minecraft",                          players: 738,  image: "src/images/minecraft.png" },
    { name: "Grand Theft Auto V",                 players: 200,  image: "src/images/grand-theft-auto-v.png" },
    { name: "Tetris",                             players: 520,  image: "src/images/tetris.png" },
    { name: "Wii Sports",                         players: 82,   image: "src/images/wii-sports.png" },
    { name: "PUBG",                               players: 400,  image: "src/images/pubg.png" },
    { name: "Mario Kart 8",                       players: 64,   image: "src/images/mario-kart-8.png" },
    { name: "Super Mario Bros.",                  players: 58,   image: "src/images/super-mario-bros.png" },
    { name: "Red Dead Redemption 2",              players: 65,   image: "src/images/red-dead-redemption-2.png" },
    { name: "The Witcher 3",                      players: 50,   image: "src/images/the-witcher-3.png" },
    { name: "Pokémon Red/Blue",                   players: 47,   image: "src/images/pokemon-red-blue.png" },
    { name: "Fortnite",                           players: 650,  image: "src/images/fortnite.png" },
    { name: "Elden Ring",                         players: 25,   image: "src/images/elden-ring.png" },
    { name: "Call of Duty: Modern Warfare",       players: 75,   image: "src/images/call-of-duty-modern-warfare.png" },
    { name: "FIFA 23",                            players: 45,   image: "src/images/fifa-23.png" },
    { name: "Among Us",                           players: 500,  image: "src/images/among-us.png" },
    { name: "Overwatch 2",                        players: 35,   image: "src/images/overwatch-2.png" },
    { name: "League of Legends",                  players: 180,  image: "src/images/league-of-legends.png" },
    { name: "Valorant",                           players: 35,   image: "src/images/valorant.png" },
    { name: "Apex Legends",                       players: 130,  image: "src/images/apex-legends.png" },
    { name: "Roblox",                             players: 380,  image: "src/images/roblox.png" },
    { name: "Counter-Strike 2",                   players: 100,  image: "src/images/counter-strike-2.png" },
    { name: "Diablo IV",                          players: 20,   image: "src/images/diablo-iv.png" },
    { name: "Hogwarts Legacy",                    players: 24,   image: "src/images/hogwarts-legacy.png" },
    { name: "The Legend of Zelda: BOTW",          players: 32,   image: "src/images/the-legend-of-zelda-botw.png" },
    { name: "God of War (2018)",                  players: 23,   image: "src/images/god-of-war-2018.png" },
    { name: "Cyberpunk 2077",                     players: 30,   image: "src/images/cyberpunk-2077.png" },
    { name: "Animal Crossing: New Horizons",      players: 44,   image: "src/images/animal-crossing-new-horizons.png" },
    { name: "The Sims 4",                         players: 70,   image: "src/images/the-sims-4.png" },
    { name: "Genshin Impact",                     players: 120,  image: "src/images/genshin-impact.png" },
    { name: "Candy Crush Saga",                   players: 500,  image: "src/images/candy-crush-saga.png" },
    { name: "Clash of Clans",                     players: 500,  image: "src/images/clash-of-clans.png" },
    { name: "Dota 2",                             players: 150,  image: "src/images/dota-2.png" },
    { name: "World of Warcraft",                  players: 150,  image: "src/images/world-of-warcraft.png" },
    { name: "Hearthstone",                        players: 150,  image: "src/images/hearthstone.png" },
    { name: "Fall Guys",                          players: 80,   image: "src/images/fall-guys.png" },
    { name: "Rocket League",                      players: 100,  image: "src/images/rocket-league.png" },
    { name: "Dark Souls III",                     players: 15,   image: "src/images/dark-souls-iii.png" },
    { name: "Sekiro: Shadows Die Twice",          players: 10,   image: "src/images/sekiro.png" },
    { name: "Monster Hunter: World",              players: 25,   image: "src/images/monster-hunter-world.png" },
    { name: "Final Fantasy VII Remake",           players: 10,   image: "src/images/final-fantasy-vii-remake.png" },
    { name: "Resident Evil Village",              players: 12,   image: "src/images/resident-evil-village.png" },
    { name: "Horizon Zero Dawn",                  players: 24,   image: "src/images/horizon-zero-dawn.png" },
    { name: "Spider-Man (PS4)",                   players: 33,   image: "src/images/spider-man-ps4.png" },
    { name: "Ghost of Tsushima",                  players: 13,   image: "src/images/ghost-of-tsushima.png" },
    { name: "Halo Infinite",                      players: 30,   image: "src/images/halo-infinite.png" },
    { name: "Destiny 2",                          players: 100,  image: "src/images/destiny-2.png" },
    { name: "Borderlands 3",                      players: 18,   image: "src/images/borderlands-3.png" },
    { name: "Sea of Thieves",                     players: 40,   image: "src/images/sea-of-thieves.png" },
    { name: "Terraria",                           players: 58,   image: "src/images/terraria.png" },
    { name: "Stardew Valley",                     players: 30,   image: "src/images/stardew-valley.png" },
    { name: "Hades",                              players: 5,    image: "src/images/hades.png" },
    { name: "Hollow Knight",                      players: 5,    image: "src/images/hollow-knight.png" },
    { name: "Celeste",                            players: 2,    image: "src/images/celeste.png" },
    { name: "Dead by Daylight",                   players: 50,   image: "src/images/dead-by-daylight.png" },
    { name: "Phasmophobia",                       players: 12,   image: "src/images/phasmophobia.png" },
    { name: "Rust",                               players: 15,   image: "src/images/rust.png" },
    { name: "ARK: Survival Evolved",              players: 20,   image: "src/images/ark-survival-evolved.png" },
    { name: "No Man's Sky",                       players: 15,   image: "src/images/no-mans-sky.png" },
    { name: "Subnautica",                         players: 8,    image: "src/images/subnautica.png" },
    { name: "The Forest",                         players: 10,   image: "src/images/the-forest.png" },
    { name: "Satisfactory",                       players: 5,    image: "src/images/satisfactory.png" },
    { name: "Factorio",                           players: 4,    image: "src/images/factorio.png" },
    { name: "Cities: Skylines",                   players: 12,   image: "src/images/cities-skylines.png" },
    { name: "Planet Coaster",                     players: 4,    image: "src/images/planet-coaster.png" },
    { name: "Euro Truck Simulator 2",             players: 15,   image: "src/images/euro-truck-simulator-2.png" },
    { name: "Microsoft Flight Simulator",         players: 10,   image: "src/images/microsoft-flight-simulator.png" },
    { name: "Farming Simulator 22",               players: 6,    image: "src/images/farming-simulator-22.png" },
    { name: "The Crew 2",                         players: 8,    image: "src/images/the-crew-2.png" },
    { name: "Forza Horizon 5",                    players: 35,   image: "src/images/forza-horizon-5.png" },
    { name: "Gran Turismo 7",                     players: 15,   image: "src/images/gran-turismo-7.png" },
    { name: "Need for Speed Heat",                players: 8,    image: "src/images/need-for-speed-heat.png" },
    { name: "Assetto Corsa",                      players: 6,    image: "src/images/assetto-corsa.png" },
    { name: "F1 23",                              players: 5,    image: "src/images/f1-23.png" },
    { name: "NBA 2K24",                           players: 20,   image: "src/images/nba-2k24.png" },
    { name: "Madden NFL 24",                      players: 15,   image: "src/images/madden-nfl-24.png" },
    { name: "MLB The Show 23",                    players: 8,    image: "src/images/mlb-the-show-23.png" },
    { name: "WWE 2K23",                           players: 6,    image: "src/images/wwe-2k23.png" },
    { name: "eFootball 2024",                     players: 50,   image: "src/images/efootball-2024.png" },
    { name: "Mortal Kombat 11",                   players: 15,   image: "src/images/mortal-kombat-11.png" },
    { name: "Street Fighter 6",                   players: 5,    image: "src/images/street-fighter-6.png" },
    { name: "Tekken 7",                           players: 12,   image: "src/images/tekken-7.png" },
    { name: "Super Smash Bros. Ultimate",         players: 33,   image: "src/images/super-smash-bros-ultimate.png" },
    { name: "Dragon Ball FighterZ",               players: 10,   image: "src/images/dragon-ball-fighterz.png" },
    { name: "Guilty Gear Strive",                 players: 3,    image: "src/images/guilty-gear-strive.png" },
    { name: "Splatoon 3",                         players: 12,   image: "src/images/splatoon-3.png" },
    { name: "Pokemon Scarlet/Violet",             players: 25,   image: "src/images/pokemon-scarlet-violet.png" },
    { name: "Pokemon GO",                         players: 600,  image: "src/images/pokemon-go.png" },
    { name: "Clash Royale",                       players: 300,  image: "src/images/clash-royale.png" },
    { name: "Brawl Stars",                        players: 400,  image: "src/images/brawl-stars.png" },
    { name: "Mobile Legends",                     players: 1000, image: "src/images/mobile-legends.png" },
    { name: "Free Fire",                          players: 1500, image: "src/images/free-fire.png" },
    { name: "PUBG Mobile",                        players: 1200, image: "https://upload.wikimedia.org/wikipedia/en/d/d4/PUBG_Mobile_logo.png" },
    { name: "Call of Duty Mobile",                players: 650,  image: "https://upload.wikimedia.org/wikipedia/en/f/f3/Call_of_Duty_Mobile_logo.png" },
    { name: "Subway Surfers",                     players: 3000, image: "https://upload.wikimedia.org/wikipedia/en/a/a4/Subway_Surfers.png" },
    { name: "Temple Run",                         players: 1000, image: "https://upload.wikimedia.org/wikipedia/en/d/d0/Temple_Run_logo.png" },
    { name: "Angry Birds",                        players: 500,  image: "https://upload.wikimedia.org/wikipedia/en/4/43/Angry_Birds_logo_2022.svg" },
    { name: "Fruit Ninja",                        players: 300,  image: "https://upload.wikimedia.org/wikipedia/en/1/14/Fruit_Ninja_logo.png" },
    { name: "Cut the Rope",                       players: 250,  image: "https://upload.wikimedia.org/wikipedia/en/c/c8/Cut_the_Rope_logo.png" },
    { name: "Plants vs. Zombies",                 players: 150,  image: "https://upload.wikimedia.org/wikipedia/en/c/c5/Plants_vs._Zombies_cover.jpg" },
    { name: "Crossy Road",                        players: 200,  image: "https://upload.wikimedia.org/wikipedia/en/9/97/Crossy_Road_logo.png" },
    { name: "8 Ball Pool",                        players: 500,  image: "https://upload.wikimedia.org/wikipedia/en/e/e8/8_Ball_Pool_app_icon.png" },
    { name: "Asphalt 9",                          players: 100,  image: "https://upload.wikimedia.org/wikipedia/en/c/cc/Asphalt_9_logo.png" },
    { name: "Geometry Dash",                      players: 100,  image: "src/images/geometry-dash.png" },
    { name: "Stumble Guys",                       players: 200,  image: "https://upload.wikimedia.org/wikipedia/en/8/81/Stumble_Guys_logo.png" },
    { name: "Human Fall Flat",                    players: 40,   image: "https://upload.wikimedia.org/wikipedia/en/6/6e/Human_Fall_Flat_cover.jpg" },
    { name: "Gang Beasts",                        players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/5/58/Gang_Beasts_Logo.png" },
    { name: "Overcooked 2",                       players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/e/e0/Overcooked_2_cover_art.png" },
    { name: "It Takes Two",                       players: 16,   image: "https://upload.wikimedia.org/wikipedia/en/c/cf/It_Takes_Two_cover_art.jpg" },
    { name: "A Way Out",                          players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/5/5c/A_Way_Out_cover.jpg" },
    { name: "Unravel Two",                        players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/0/00/Unravel_Two.jpg" },
    { name: "Little Nightmares II",               players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/a/a8/Little_Nightmares_II_cover_art.jpg" },
    { name: "Inside",                             players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/5/5d/Inside_%28video_game%29_cover_art.png" },
    { name: "Limbo",                              players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/c/cc/Limbo_Box_Art.jpg" },
    { name: "Cuphead",                            players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/5/50/Cuphead_%28artwork%29.png" },
    { name: "Ori and the Will of the Wisps",      players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/2/2d/Ori_and_the_Will_of_the_Wisps_cover_art.jpg" },
    { name: "Psychonauts 2",                      players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/0/00/Psychonauts_2_cover_art.jpg" },
    { name: "Ratchet & Clank: Rift Apart",        players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/8/8b/Ratchet_%26_Clank_-_Rift_Apart.png" },
    { name: "Sackboy: A Big Adventure",           players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/d/de/Sackboy_A_Big_Adventure.jpg" },
    { name: "Astro's Playroom",                   players: 20,   image: "https://upload.wikimedia.org/wikipedia/en/0/05/Astro%27s_Playroom_cover_art.jpg" },
    { name: "Returnal",                           players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/1/1d/Returnal_cover_art.png" },
    { name: "Deathloop",                          players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/9/99/Deathloop.jpg" },
    { name: "Hitman 3",                           players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/0/0a/Hitman_3_Packart.jpg" },
    { name: "Dishonored 2",                       players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/a/ab/Dishonored_2_cover_art.jpg" },
    { name: "Prey (2017)",                        players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/a/a2/Prey_cover_art.jpg" },
    { name: "Control",                            players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/8/88/Control_cover_art.png" },
    { name: "Alan Wake 2",                        players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/e/e5/Alan_Wake_2_cover_art.jpg" },
    { name: "Death Stranding",                    players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/2/22/Death_Stranding.jpg" },
    { name: "Metal Gear Solid V",                 players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/8/8e/MGSV_The_Phantom_Pain_boxart.jpg" },
    { name: "Assassin's Creed Valhalla",          players: 25,   image: "https://upload.wikimedia.org/wikipedia/en/e/e3/Assassin%27s_Creed_Valhalla_cover.jpg" },
    { name: "Far Cry 6",                          players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/3/35/FC6_box_art.jpg" },
    { name: "Watch Dogs Legion",                  players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/6/60/WatchDogsLegion.jpg" },
    { name: "Rainbow Six Siege",                  players: 85,   image: "https://upload.wikimedia.org/wikipedia/en/4/47/Tom_Clancy%27s_Rainbow_Six_Siege_cover_art.jpg" },
    { name: "The Division 2",                     players: 20,   image: "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Division_2_art.jpg" },
    { name: "Ghost Recon Wildlands",              players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/2/2b/Tom_Clancy%27s_Ghost_Recon_Wildlands_cover_art.jpg" },
    { name: "For Honor",                          players: 25,   image: "https://upload.wikimedia.org/wikipedia/en/f/fe/For_Honor_cover_art.jpg" },
    { name: "Steep",                              players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/9/9f/Steep_video_game_cover.jpg" },
    { name: "Riders Republic",                    players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/7/7d/Riders_Republic_cover_art.jpg" },
    { name: "Just Dance 2024",                    players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/5/57/Just_Dance_2024_Edition_cover_art.jpg" },
    { name: "Beat Saber",                         players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/1/17/Beat_Saber_Logo.png" },
    { name: "Half-Life: Alyx",                    players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/c/cf/Half-Life_Alyx_Cover_Art.jpg" },
    { name: "The Elder Scrolls V: Skyrim",        players: 60,   image: "https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png" },
    { name: "Fallout 4",                          players: 25,   image: "https://upload.wikimedia.org/wikipedia/en/7/70/Fallout_4_cover_art.jpg" },
    { name: "Starfield",                          players: 14,   image: "https://upload.wikimedia.org/wikipedia/en/6/6b/Starfield_cover.jpg" },
    { name: "Baldur's Gate 3",                    players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/1/12/Baldur%27s_Gate_3_cover_art.jpg" },
    { name: "Divinity: Original Sin 2",           players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/5/5e/Divinity_Original_Sin_II_cover_art.jpg" },
    { name: "Disco Elysium",                      players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/0/01/Disco_Elysium_cover_art.jpg" },
    { name: "Persona 5 Royal",                    players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/b/b0/Persona_5_Royal.jpg" },
    { name: "Fire Emblem: Three Houses",          players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/1/16/Fire_Emblem_Three_Houses.jpg" },
    { name: "Xenoblade Chronicles 3",             players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/1/1a/Xenoblade_Chronicles_3_cover_art.png" },
    { name: "Tales of Arise",                     players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/7/71/Tales_of_Arise_logo.png" },
    { name: "Triangle Strategy",                  players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/5/55/Triangle_Strategy_cover_art.jpg" },
    { name: "Octopath Traveler II",               players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/7/7e/Octopath_Traveler_II_cover_art.jpg" },
    { name: "Live A Live",                        players: 1,    image: "https://upload.wikimedia.org/wikipedia/en/8/8e/Live_A_Live_2022_cover.jpg" },
    { name: "Crisis Core Final Fantasy VII",      players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Crisis_Core_Reunion_cover.jpg" },
    { name: "Bravely Default II",                 players: 1,    image: "https://upload.wikimedia.org/wikipedia/en/a/a3/Bravely_Default_II_cover_art.jpg" },
    { name: "Dragon Quest XI",                    players: 7,    image: "https://upload.wikimedia.org/wikipedia/en/b/b0/Dragon_Quest_XI_cover_art.jpg" },
    { name: "Nier: Automata",                     players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/2/21/Nier_Automata_cover_art.jpg" },
    { name: "Kingdom Hearts III",                 players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/5/5a/Kingdom_Hearts_III_box_art.jpg" },
    { name: "Final Fantasy XVI",                  players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/0/0e/Final_Fantasy_XVI_cover_art.png" },
    { name: "Star Wars Jedi: Survivor",           players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/e/e6/Star_Wars_Jedi_Survivor_key_art.jpg" },
    { name: "Star Wars Jedi: Fallen Order",       players: 20,   image: "https://upload.wikimedia.org/wikipedia/en/1/12/Star_Wars_Jedi_Fallen_Order.png" },
    { name: "Lego Star Wars: Skywalker Saga",     players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/d/d4/Lego_Star_Wars_The_Skywalker_Saga_cover.jpg" },
    { name: "Lego Marvel Super Heroes",           players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/7/7f/Lego_Marvel_Super_Heroes.jpg" },
    { name: "Lego Batman 3",                      players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/6/6c/Lego_Batman_3.jpg" },
    { name: "Crash Bandicoot 4",                  players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/3/3d/Crash_Bandicoot_4_-_It%27s_About_Time_cover_art.jpg" },
    { name: "Spyro Reignited Trilogy",            players: 10,   image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Spyro_Reignited_Trilogy.jpg" },
    { name: "Sonic Frontiers",                    players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/2/22/Sonic_Frontiers_cover.jpg" },
    { name: "Sonic Mania",                        players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/8/8e/Sonic_Mania_key_art.jpg" },
    { name: "Kirby and the Forgotten Land",       players: 6,    image: "https://upload.wikimedia.org/wikipedia/en/1/17/Kirby_and_the_Forgotten_Land_box_art.jpg" },
    { name: "Yoshi's Crafted World",              players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/0/08/Yoshi%27s_Crafted_World.jpg" },
    { name: "Donkey Kong Country: TF",            players: 5,    image: "https://upload.wikimedia.org/wikipedia/en/1/18/DKCTF_WiiU_EN_boxart.png" },
    { name: "New Super Mario Bros. U",            players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/b/bf/New_Super_Mario_Bros._U_box_art.png" },
    { name: "Super Mario 3D World",               players: 13,   image: "https://upload.wikimedia.org/wikipedia/en/8/8c/Super_Mario_3D_World_%2B_Bowser%27s_Fury.jpg" },
    { name: "Super Mario Odyssey",                players: 27,   image: "https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg" },
    { name: "Luigi's Mansion 3",                  players: 12,   image: "https://upload.wikimedia.org/wikipedia/en/5/5f/Luigi%27s_Mansion_3_cover_art.jpg" },
    { name: "Paper Mario: Origami King",          players: 4,    image: "https://upload.wikimedia.org/wikipedia/en/c/c2/Paper_Mario_-_The_Origami_King.jpg" },
    { name: "Super Mario Maker 2",                players: 8,    image: "https://upload.wikimedia.org/wikipedia/en/7/76/Super_Mario_Maker_2.jpg" },
    { name: "New Pokémon Snap",                   players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/1/1e/New_Pokemon_Snap_cover_art.png" },
    { name: "Pokémon Legends: Arceus",            players: 15,   image: "https://upload.wikimedia.org/wikipedia/en/0/0e/Pok%C3%A9mon_Legends_-_Arceus_logo.png" },
    { name: "Pokémon Sword/Shield",               players: 26,   image: "https://upload.wikimedia.org/wikipedia/en/b/b6/Pok%C3%A9mon_Sword_and_Shield_logo.png" },
    { name: "Metroid Dread",                      players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/d/df/Metroid_Dread_cover.jpg" },
    { name: "The Legend of Zelda: TOTK",          players: 21,   image: "https://upload.wikimedia.org/wikipedia/en/f/fc/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg" },
    { name: "Link's Awakening (2019)",            players: 7,    image: "https://upload.wikimedia.org/wikipedia/en/a/a5/The_Legend_of_Zelda_Link%27s_Awakening_%282019%29_cover.jpg%22"},
    { name: "Pikmin 4",                           players: 3,    image: "https://upload.wikimedia.org/wikipedia/en/a/a4/Pikmin_4_cover_art.png" },
    { name: "Bayonetta 3",                        players: 2,    image: "https://upload.wikimedia.org/wikipedia/en/6/69/Bayonetta_3_cover_art.jpg" },
];
 
export default games;